services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5433:5433
    volumes:
      - ./postgres:/var/lib/postgresql/data

  api:
    image: biairmal/tps-api:https
    restart: always
    command: sh -c './wait-for-it.sh postgres:5432 -- yarn sequelize:seed:prod ; node src/index.js'
    ports:
      - 8080:${HTTP_PORT}
      - 8443:${HTTPS_PORT}
    depends_on:
      - postgres
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
      - NODE_ENV=${API_NODE_ENV}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=${DB_HOST}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN}